### ISSUE TITLE
Different arrival times [feature request]

### ISSUE THREAD

**Issue by Maros112358** [jolibrain/wheatley#89]
Hello, I would like to solve a JSSP problem with different arrival times. Some of the jobs should be available at start `t = 0`, and others should arrive at time `t > 0`. I tried to use Wheatley for this purpose, but as far as I know, it does not support this feature right now. Would it be possible to add this feature to Wheatley?

**Comment by Maros112358** [comment]
Hello @fantes, thank you for the quick reply. I think it sounds reasonable. Are you planning to implement this in the near future? Or can this be done with Wheatley right now?

**Comment by fantes** [comment]
Using the rcpsp code, this should work directly by adding such jobs in the problem description file.
In jssp this is a bit more complicated, as tasks have to use a resource so this implies also adding extra "virtual" resources, one per such virtual task in order to be sure that they do not interfere.  (a -1 in the description file means that the tasks should not be scheduled at all, not that it does not use any resource). Hope this helps

**Comment by Maros112358** [comment]
Hello @fantes, I tried implementing the proposed solution, and I would like to just make a quick check with an example if I understood you correctly.

This is 6x6 JSSP instance in Taillard specification
```
6	6
1	3	6	7	3	6
8	5	10	10	10	4
5	4	8	9	1	7
5	5	5	3	8	9
9	3	5	4	3	1
3	3	9	10	4	1
3	1	2	4	6	5
2	3	5	6	1	4
3	4	6	1	2	5
2	1	3	4	5	6
3	2	5	6	1	4
2	4	6	1	5	3
```
For each job, I generated arrival times [7, 0, 0, 5, 8, 0] (first job starts at time 7, second at 0, ...). The JSSP instance in Taillard specification with virtual tasks should then look like this:
```
6	6
7      1	3	6	7	3	6
8	5	10	10	10	4
5	4	8	9	1	7
5	5	5	5	3	8	9
8	9	3	5	4	3	1
3	3	9	10	4	1
7	3	1	2	4	6	5
2	3	5	6	1	4
3	4	6	1	2	5
8	2	1	3	4	5	6
9	3	2	5	6	1	4
2	4	6	1	5	3
```

If it's correct, I can prepare a pull request with the code snippet I used.

**Comment by fantes** [comment]
Hello @Maros112358 
I think the reader/parser will not be able to read files with holes. I would try to also add tasks with a duration of zero (at beginning of jobs 2,3 and 6) and specify that the jssp problem is of size 7 x 6 (or 6x7, I cannot remember which one is number of tasks/number of jobs). Wheatley should be able to deal with null durations directly. I am less sure for ortools/cp-sat, you will have to test. Hope this helps.

**Comment by Maros112358** [comment]
Hello @fantes,
it worked correctly even with holes. Wheatley filled the rest automatically.

**Comment by fantes** [comment]
ok, that is pretty cool. Just keep in mind that we did not test this case, so do not hesitate to double/triple check the results.
